theme                    : jekyll-theme-cayman
title                    : "Dr. Raquel Guimaraes"
tagline                  : Welcome to my professional page!
name                     : &name "Raquel Guimaraes"
description              : &description "Welcome to my professional page!"

baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Raquel Guimaraes
  
# Gems
gems:
  - jekyll-paginate