theme                    : jekyll-theme-cayman
title                    : "Raquel Guimaraes' webpage"
name                     : &name "Raquel Guimaraes"
description              : &description "Academic cv and current affiliation"
