title: Dr. Raquel Guimaraes
description: Welcome to my professional webpage.
show_downloads: true
google_analytics: UA-61866064-2
theme: jekyll-theme-cayman

baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Raquel Guimaraes
  
# Gems
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

#Others
markdown: kramdown

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
  
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
